markdown: redcarpet
pygments: true

title_tag_text: 'CSE Undergrad @ IIT Bombay' 
h1_tag_text: Prithviraj M Billa

exclude: ["Procfile", "Gruntfile.js", "README.md", "package.json", "CNAME", "node_modules"]
